### ISSUE TITLE
Waydroid does not start

### ISSUE THREAD

**Issue by ticklemyIP** [ublue-os/bazzite#1572]
### Describe the bug

I have been trying to make waydroid work, to no avail, first the container service was throwing errors and exiting, which I was able to solve by `sudo setenforce 0', however the errors are still the same.

### What did you expect to happen?

I expect waydroid to work without issue.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:40459f00ad4ef337c3923afa48bb57d29208c049db8569a7f53d446c3f1f1afa
                  Version: 40.20240826.0 (2024-08-27T06:57:15Z)
          LayeredPackages: syncthing
            LocalPackages: lact-0.5.5-0.x86_64 windscribe-2.10.15-0.x86_64
             InitramfsEtc: /etc/vconsole.conf

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:40459f00ad4ef337c3923afa48bb57d29208c049db8569a7f53d446c3f1f1afa
                  Version: 40.20240826.0 (2024-08-27T06:57:15Z)
          LayeredPackages: syncthing
            LocalPackages: lact-0.5.5-0.x86_64 windscribe-2.10.15-0.x86_64
             InitramfsEtc: /etc/vconsole.conf
```

### Hardware

PC x86 AMD iGPU, Vega 8 Graphics

### Extra information or context

LOGS

sudo systemctl enable --now waydroid-container
```
Job for waydroid-container.service failed because the control process exited with error code.
See "systemctl status waydroid-container.service" and "journalctl -xeu waydroid-container.service" for details.
```
journalctl -xeu waydroid-container.service
```
Aug 29 13:36:19 bazzite systemd[1]: Starting waydroid-container.service - Waydroid Container...
░░ Subject: A start job for unit waydroid-container.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has begun execution.
░░ 
░░ The job identifier is 400.
Aug 29 13:36:20 bazzite waydroid[2378]: Run 'waydroid log' for details. Alternatively you can use '--details-to-stdout' to get more output, e.g. 'waydroid --details-to-stdout init'.
Aug 29 13:36:20 bazzite systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit waydroid-container.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Aug 29 13:36:20 bazzite systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit waydroid-container.service has entered the 'failed' state with result 'exit-code'.
Aug 29 13:36:20 bazzite systemd[1]: Failed to start waydroid-container.service - Waydroid Container.
░░ Subject: A start job for unit waydroid-container.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has finished with a failure.
░░ 
░░ The job identifier is 400 and the job result is failed.
Aug 29 13:38:32 device systemd[1]: Starting waydroid-container.service - Waydroid Container...
░░ Subject: A start job for unit waydroid-container.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has begun execution.
░░ 
░░ The job identifier is 5289.
Aug 29 13:38:32 device waydroid[7308]: Run 'waydroid log' for details. Alternatively you can use '--details-to-stdout' to get more output, e.g. 'waydroid --details-to-stdout init'.
Aug 29 13:38:32 device systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit waydroid-container.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Aug 29 13:38:32 device systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit waydroid-container.service has entered the 'failed' state with result 'exit-code'.
Aug 29 13:38:32 device systemd[1]: Failed to start waydroid-container.service - Waydroid Container.
░░ Subject: A start job for unit waydroid-container.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has finished with a failure.
░░ 
░░ The job identifier is 5289 and the job result is failed.
Aug 29 13:38:58 device systemd[1]: Starting waydroid-container.service - Waydroid Container...
░░ Subject: A start job for unit waydroid-container.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has begun execution.
░░ 
░░ The job identifier is 5812.
Aug 29 13:38:58 device waydroid[7458]: Run 'waydroid log' for details. Alternatively you can use '--details-to-stdout' to get more output, e.g. 'waydroid --details-to-stdout init'.
Aug 29 13:38:58 device systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit waydroid-container.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Aug 29 13:38:58 device systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit waydroid-container.service has entered the 'failed' state with result 'exit-code'.
Aug 29 13:38:58 device systemd[1]: Failed to start waydroid-container.service - Waydroid Container.
░░ Subject: A start job for unit waydroid-container.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has finished with a failure.
░░ 
░░ The job identifier is 5812 and the job result is failed.
```
sudo waydroid container start
```
ERROR: WayDroid is not initialized, run "waydroid init"
```
sudo waydroid session start
```
ERROR: WayDroid is not initialized, run "waydroid init"
```
sudo waydroid init
```
[13:45:37] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
[13:45:37] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
 sudo setenforce 0

I checked the service, it runs, waydroid app after pressing download button displays `Waiting for waydroid container service...`

sudo waydroid container start
```
ERROR: WayDroid is not initialized, run "waydroid init"
```
sudo waydroid init
```
[13:45:37] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
[13:45:37] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
waydroid log
```
(007890) [13:23:15] See also: <https://github.com/waydroid>
(007890) [13:23:15] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1

(007914) [13:23:19] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(007914) [13:23:19] *** output passed to waydroid stdout, not to this log ***
(008423) [13:44:38] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
(008423) [13:44:38] See also: <https://github.com/waydroid>
(008423) [13:44:38] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1

(008322) [13:44:48] Introspect error on :1.162:/Initializer: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
(008322) [13:44:48] Executing introspect queue due to error
(008458) [13:44:55] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
(008458) [13:44:55] See also: <https://github.com/waydroid>
(008458) [13:44:55] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1

(008478) [13:45:11] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
(008478) [13:45:11] See also: <https://github.com/waydroid>
(008478) [13:45:11] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1

(008500) [13:45:37] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
(008500) [13:45:37] See also: <https://github.com/waydroid>
(008500) [13:45:37] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1

(008539) [13:46:24] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(008539) [13:46:24] *** output passed to waydroid stdout, not to this log ***
```

**Comment by KyleGospo** [comment]
Please re enable SELinux, then follow our setup guide.

**Comment by shawny43** [comment]
> Please re-enable SELinux, then follow our setup guide.

There no guides to enable SELinux in Bazzite. It's not make sense. You tell a user that doesn't experimented with kernels and criticals contents. How we could enable this safely without trashing the desktop? Is the question.

**Comment by KyleGospo** [comment]
> > Please re-enable SELinux, then follow our setup guide.
> 
> There no guides to enable SELinux in Bazzite. It's not make sense. You tell a user that doesn't experimented with kernels and criticals contents. How we could enable this safely without trashing the desktop? Is the question. 

It is enabled by default, If the user turned it off it is expected they know how to turn it back on.

**Comment by KyleGospo** [comment]
In that case please open a new issue and provide all of the logs that you can and we can take a look

**Comment by shawny43** [comment]
> In that case please open a new issue and provide all of the logs that you can and we can take a look.
> 
> I can at least confirm that this does not happen to me so whatever it is it should be fixable.

Already created. I don't want to be accused of copy-pasta or somewhat duplicate but if you said i needs to create one, i did.
