### ISSUE TITLE
[Just] Failed `update-system` command

### ISSUE THREAD

**Issue by beefchimi** [ublue-os/bazzite#326]
I ran the `just update-system` command and it appears to have failed for a few reasons. Here is the output:

```log
[beefchimi@fedora beefchimi]$ just update-system
/usr/bin/ublue-update
[2023-09-18 21:35:11,133] ublue_update.update_inhibitors.hardware:INFO | System passed hardware checks
[2023-09-18 21:35:11,133] ublue_update.cli:INFO | System passed all update checks
[2023-09-18 21:35:11,198] ublue_update.cli:INFO | Running update script: /etc/ublue-update.d/user/00-flatpak-user-update.sh
[2023-09-18 21:35:11,392] ublue_update.cli:INFO | Running update script: /etc/ublue-update.d/user/01-flatpak-user-repair-cleanup.sh
[2023-09-18 21:35:30,453] ublue_update.cli:INFO | Running update script: /etc/ublue-update.d/user/02-distrobox-user-update.sh
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/ublue-update", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.11/site-packages/ublue_update/cli.py", line 260, in main
    run_updates(cli_args)
  File "/usr/lib/python3.11/site-packages/ublue_update/cli.py", line 187, in run_updates
    run_update_scripts(f"{root_dir}/user/")
  File "/usr/lib/python3.11/site-packages/ublue_update/cli.py", line 110, in run_update_scripts
    log.error(
Message: '/etc/ublue-update.d/user/02-distrobox-user-update.sh returned error code: 125'
Arguments: ('',)
[2023-09-18 21:35:30,629] ublue_update.cli:INFO | Running update script: /etc/ublue-update.d/user/03-fleek-user-update.sh
[2023-09-18 21:35:30,630] ublue_update.cli:INFO | Running update script: /etc/ublue-update.d/user/99-bazzite-arch-user-update.sh
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/ublue-update", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.11/site-packages/ublue_update/cli.py", line 260, in main
    run_updates(cli_args)
  File "/usr/lib/python3.11/site-packages/ublue_update/cli.py", line 187, in run_updates
    run_update_scripts(f"{root_dir}/user/")
  File "/usr/lib/python3.11/site-packages/ublue_update/cli.py", line 110, in run_update_scripts
    log.error(
Message: '/etc/ublue-update.d/user/99-bazzite-arch-user-update.sh returned error code: 125'
Arguments: ('',)
```

**Comment by KyleGospo** [comment]
@gerblesh

**Comment by trigg** [comment]
I've just hit this problem myself, further poking gets more data
```
$ /etc/ublue-update.d/user/99-bazzite-arch-user-update.sh 
Container bazzite-arch is not running.
Starting container bazzite-arch
run this command to follow along:

 podman logs -f bazzite-arch

Error: unable to start container "6e2a8d052dade0bb2e69d5620e1c2aa985496016670a6791a40a39af80524131": crun: error stat'ing file `/usr/lib/extest/libextest.so`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

**Comment by KyleGospo** [comment]
> I've just hit this problem myself, further poking gets more data

Running `just install-bazzite-arch` should clear this up, we had a breaking change recently due to Nvidia, should be the only one like it.

**Comment by trigg** [comment]
That did it for me! Thank you

**Comment by beefchimi** [comment]
This command also got things working for me - thank you! Shall we go ahead and close the issue?
